### ISSUE TITLE
Unable to merge material

### ISSUE THREAD

**Issue by NyaSita47** [Grim-es/material-combiner-addon#109]
![image](https://github.com/user-attachments/assets/7d094a46-95b2-4697-8995-af01be716590)

**Comment by Grim-es** [comment]
Hello, it seems the issue may be due to the PIL library being unable to read your files. You can try unpacking the textures by going to File > External Data > Unpack Files/Resources. After that, re-save the textures as PNG files using any image editing software (even if they are already in PNG format), restart Blender, and try again.

If the issue persists, try rebuilding all the nodes for each material. Replace the `MMD` shader with a `Diffuse BSDF` and delete every node except the `Image Texture` (with the main texture you want to atlas), the newly added `Diffuse BSDF`, and the `Material Output`.

**Comment by NyaSita47** [comment]
ok ,thank you❤❤
