### ISSUE TITLE
2.93 - No error thrown, but materials don't combine, no save dialogue opens, no texture atlas

### ISSUE THREAD

**Issue by tdw46** [Grim-es/material-combiner-addon#29]
https://user-images.githubusercontent.com/10996763/131235353-51a3f4d0-2b9c-4107-b27c-150de566448e.mp4

![image](https://user-images.githubusercontent.com/10996763/131235407-4549c1e4-db22-420f-86cd-18c96d67a79d.png)

**Comment by TemperanceTempy** [comment]
Also having this issue, any way to fix this?
![Screenshot (760)](https://user-images.githubusercontent.com/57856324/147839412-bd556302-b3d2-4ce3-af68-38b6e6d38fa6.png)
![Screenshot (761)](https://user-images.githubusercontent.com/57856324/147839413-da1a2683-a767-4925-b31e-b384c7e01827.png)

**Comment by rowantobias** [comment]
having this issue myself. not sure what to do about it.
![1](https://user-images.githubusercontent.com/11569229/150885085-7ee3ed4d-e953-4efd-9601-5d60c945dcbe.png)
![2](https://user-images.githubusercontent.com/11569229/150885095-5cbeadad-a5e7-4fdb-aa45-d396e3c3ee8c.png)

**Comment by Grim-es** [comment]
Hello, combining materials instead of generating an atlas can occur for several reasons, this happens because the combiner cannot find image files on disk. The main reasons for this behavior are:
1. The textures are packed in a .blend file, so you need to click on File>External data>Unpack All Into Files.
2. Your version of Blender is not in English, in this case the nodes will be named differently, since their names are strictly specified in the script, they will not be found and paths to images cannot be taken.
3. You are using an unsupported shader (the surface property of materials). You can look in the [utils/materials.py](https://github.com/Grim-es/material-combiner-addon/blob/master/utils/materials.py) file to see what shaders are available or what names the nodes should have in order for the combiner to find the paths to the images.

**Comment by AlexMassenzio** [comment]
> Hello, combining materials instead of generating an atlas can occur for several reasons, this happens because the combiner cannot find image files on disk. The main reasons for this behavior are:
> 
> 1. The textures are packed in a .blend file, so you need to click on File>External data>Unpack All Into Files.
> 2. Your version of Blender is not in English, in this case the nodes will be named differently, since their names are strictly specified in the script, they will not be found and paths to images cannot be taken.
> 3. You are using an unsupported shader (the surface property of materials). You can look in the [utils/materials.py](https://github.com/Grim-es/material-combiner-addon/blob/master/utils/materials.py) file to see what shaders are available or what names the nodes should have in order for the combiner to find the paths to the images.

Was running into the same issue and the first step fixed the issue for me. Specifically selected "Write files to current directory (overwrite existing files)", but I didn't test the other options so they might work as well.

**Comment by Matheo-bis** [comment]
> Hello, combining materials instead of generating an atlas can occur for several reasons, this happens because the combiner cannot find image files on disk. The main reasons for this behavior are:
> 
>     1. The textures are packed in a .blend file, so you need to click on File>External data>Unpack All Into Files.
> 
>     2. Your version of Blender is not in English, in this case the nodes will be named differently, since their names are strictly specified in the script, they will not be found and paths to images cannot be taken.
> 
>     3. You are using an unsupported shader (the surface property of materials). You can look in the [utils/materials.py](https://github.com/Grim-es/material-combiner-addon/blob/master/utils/materials.py) file to see what shaders are available or what names the nodes should have in order for the combiner to find the paths to the images.

Thanks for the insight, I had another issue than this one and Unpacking textures solved it
